services:
  orders-database:
    container_name: orders-database
    image: postgres:16.2
    restart: always
    volumes:
      - ./postgres:/var/lib/postgresl/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=orders
